import path from "node:path";

import { isCancel, multiselect } from "@clack/prompts";
import { z } from "zod";

import { createBlueprintSchema, diffText } from "@vibestart/core";
import { registry } from "@vibestart/integrations";

import {
  assertCleanWorktree,
  checksOf,
  commandLine,
  installAndCheck,
  installStep,
  undoHint,
  writePlan,
} from "#/maintenance/apply.ts";
import { readText } from "#/maintenance/files.ts";
import {
  MaintenanceError,
  normalizeInput,
  projectOf,
  recordFile,
  serialize,
} from "#/maintenance/model.ts";
import type { Input, Project } from "#/maintenance/model.ts";
import type { Options } from "#/maintenance/options.ts";
import {
  approve,
  interactive,
  options,
  usage,
  validateOptions,
} from "#/maintenance/options.ts";
import { maintenanceText } from "#/maintenance/output.ts";
import type { Plan } from "#/maintenance/plan.ts";
import { planUpdate } from "#/maintenance/plan.ts";
import {
  currentSnapshot,
  latestVersion,
  runningVersion,
  snapshotAt,
} from "#/maintenance/release.ts";
import { loadRecipe } from "#/stack.ts";

const names = new Set(["add", "doctor", "upgrade", "snapshot"]);
export const isMaintenanceCommand = (name: string | undefined) =>
  name !== undefined && names.has(name);

const capabilities = () => [
  ...registry.addons
    .filter((addon) => addon.supportsAdd === true)
    .map(({ id, name, description }) => ({
      description,
      id,
      kind: "extension",
      name,
    })),
  ...registry.integrations
    .filter((integration) => integration.supportsAdd === true)
    .map(({ id, name, description, kind }) => ({
      description,
      id,
      kind,
      name,
    })),
];

const readProject = async (cwd: string) => projectOf(await loadRecipe(cwd));

const added = async (
  project: Project,
  ids: readonly string[],
  values: Options
): Promise<Input> => {
  if (project.version !== runningVersion) {
    throw new MaintenanceError(
      `requires-upgrade: the project was generated by ${project.version}; run vibestart upgrade with this release (${runningVersion}) before adding capabilities.`
    );
  }
  let selected = [...ids];
  if (selected.length === 0 && interactive() && !values.json) {
    const answer = await multiselect({
      message: "Add capabilities",
      options: capabilities().map(({ id, name, description }) => ({
        hint: description,
        label: name,
        value: id,
      })),
      required: true,
    });
    if (isCancel(answer)) {
      throw new MaintenanceError("Cancelled", 130);
    }
    selected = answer;
  }
  if (selected.length === 0) {
    throw new MaintenanceError(
      "Choose a capability; see vibestart add --list.",
      2
    );
  }
  const blueprint = {
    ...project.blueprint,
    addons: [...project.blueprint.addons],
    stack: { ...project.blueprint.stack },
  };
  for (const id of selected) {
    const capability = capabilities().find((item) => item.id === id);
    if (capability === undefined) {
      throw new MaintenanceError(
        `Cannot add ${id}. This release supports: ${capabilities()
          .map((item) => item.id)
          .join(", ")}`,
        2
      );
    }
    if (capability.kind === "extension") {
      blueprint.addons = [...new Set([...blueprint.addons, id])];
    } else {
      const previous = blueprint.stack[capability.kind];
      if (previous !== undefined && previous !== id) {
        throw new MaintenanceError(
          `Adding ${id} would replace ${previous}; this needs an explicit migration.`
        );
      }
      blueprint.stack[capability.kind] = id;
    }
  }
  return blueprint;
};

const planFor = async (
  command: string,
  cwd: string,
  ids: readonly string[],
  values: Options
) => {
  const project = await readProject(cwd);
  if (command === "add") {
    const blueprint = await added(project, ids, values);
    return planUpdate(
      cwd,
      await currentSnapshot(project.name, project.blueprint),
      await currentSnapshot(project.name, blueprint)
    );
  }
  return planUpdate(
    cwd,
    await snapshotAt(project.version, project),
    await snapshotAt(values.to ?? runningVersion, project)
  );
};

const inspect = async (cwd: string, offline: boolean) => {
  const project = await readProject(cwd);
  const issues: string[] = [];
  const manifest = z
    .object({
      devEngines: z
        .object({ packageManager: z.object({ name: z.string() }) })
        .optional(),
      packageManager: z.string().optional(),
    })
    .parse(JSON.parse(readText(cwd, "package.json") ?? "{}"));
  const manager =
    manifest.packageManager?.split("@")[0] ??
    manifest.devEngines?.packageManager.name;
  if (manager !== project.blueprint.packageManager) {
    issues.push(`package.json disagrees with ${recordFile}'s package manager.`);
  }
  const lockfile =
    project.blueprint.packageManager === "bun" ? "bun.lock" : "pnpm-lock.yaml";
  if (readText(cwd, lockfile) === null) {
    issues.push(`Missing ${lockfile}: run vp install`);
  }
  // Another release's templates come from npm, which --offline rules out.
  const plan =
    offline && project.version !== runningVersion
      ? null
      : planUpdate(
          cwd,
          await snapshotAt(project.version, project),
          await currentSnapshot(project.name, project.blueprint)
        );
  const conflicts = plan?.conflicts.map(({ path: file }) => file) ?? [];
  return {
    conflicts,
    issues,
    latest: offline ? null : await latestVersion().catch(() => null),
    manual: plan?.manual.length ?? null,
    release: project.version,
    status: issues.length > 0 || conflicts.length > 0 ? "attention" : "healthy",
    updates: plan?.changes.length ?? null,
  };
};

interface Outcome {
  readonly exitCode: number;
  readonly status: string;
}

interface Listing extends Outcome {
  readonly capabilities: ReturnType<typeof capabilities>;
}

type Health = Outcome & Awaited<ReturnType<typeof inspect>>;

interface Planned extends Outcome {
  readonly changes: Plan["changes"];
  readonly conflicts: readonly string[];
  readonly manual: Plan["manual"];
  readonly release: string;
  readonly next?: string;
}

export type MaintenanceResult = Listing | Health | Planned;

const printPlan = (plan: Plan) => {
  process.stdout.write(
    `${plan.changes.length} file changes, ${plan.conflicts.length} conflicts\n`
  );
  for (const change of plan.changes) {
    process.stdout.write(`${diffText(change)}\n`);
  }
  if (plan.manual.length > 0) {
    process.stdout.write(
      `\n${plan.manual.length} template changes to files the project owns, to port by hand (never written):\n`
    );
    for (const change of plan.manual) {
      process.stdout.write(`${diffText(change)}\n`);
    }
  }
};

const execute = async (
  command: string,
  ids: readonly string[],
  values: Options
): Promise<MaintenanceResult> => {
  const cwd = path.resolve(values.cwd);
  if (command === "add" && values.list) {
    return { capabilities: capabilities(), exitCode: 0, status: "available" };
  }
  if (command === "doctor") {
    const result = await inspect(cwd, values.offline ?? false);
    return { ...result, exitCode: result.status === "healthy" ? 0 : 1 };
  }
  const plan = await planFor(command, cwd, ids, values);
  const result = {
    changes: plan.changes,
    conflicts: plan.conflicts.map(({ path: file }) => file),
    manual: plan.manual,
    release: plan.target.version,
  };
  if (!values.json) {
    printPlan(plan);
  }
  if (plan.changes.length === 0 && plan.manual.length === 0) {
    return { ...result, exitCode: 0, status: "no-op" };
  }
  if (values.check || values["dry-run"]) {
    return plan.conflicts.length > 0
      ? {
          ...result,
          exitCode: 1,
          status: "conflicts",
          next: "Preview only; no files were written. Applying writes conflict markers into these files for you to resolve.",
        }
      : { ...result, exitCode: values.check ? 1 : 0, status: "planned" };
  }
  await assertCleanWorktree(cwd);
  await approve(values);
  writePlan(cwd, plan);
  const port =
    plan.manual.length > 0
      ? ["Port the template changes listed under manual by hand."]
      : [];
  const checks = checksOf(cwd, plan, values["full-check"]);
  const finish = `${commandLine([installStep, ...checks])}.`;
  if (plan.conflicts.length > 0) {
    return {
      ...result,
      exitCode: 1,
      status: "conflicts",
      next: [
        `Resolve the conflict markers in these files, then run ${finish}`,
        ...port,
        undoHint,
      ].join(" "),
    };
  }
  if (values["no-install"]) {
    return {
      ...result,
      exitCode: 0,
      status: "needs-install",
      next: [finish, ...port].join(" "),
    };
  }
  await installAndCheck(cwd, checks);
  const completed = { ...result, exitCode: 0, status: "completed" };
  return port.length === 0 ? completed : { ...completed, next: port.join(" ") };
};

export const maintenanceCommand = async (args: readonly string[]) => {
  const json = args.includes("--json");
  try {
    const { values, positionals } = options(args.slice(1));
    if (values.help) {
      process.stdout.write(
        json
          ? serialize({ exitCode: 0, ok: true, status: "help", usage })
          : usage
      );
      return 0;
    }
    const command = args[0] ?? "";
    validateOptions(command, positionals, values);
    if (command === "snapshot") {
      let text = "";
      for await (const chunk of process.stdin) {
        text += String(chunk);
      }
      const input = z
        .object({
          blueprint: createBlueprintSchema(registry),
          name: z.string(),
        })
        .parse(JSON.parse(text));
      process.stdout.write(
        serialize(
          await currentSnapshot(input.name, normalizeInput(input.blueprint))
        )
      );
      return 0;
    }
    const result = await execute(command, positionals, values);
    process.stdout.write(
      json
        ? `${JSON.stringify({ ...result, ok: result.exitCode === 0 }, null, 2)}\n`
        : maintenanceText(result, values.offline)
    );
    return result.exitCode;
  } catch (error) {
    const exitCode = error instanceof MaintenanceError ? error.exitCode : 1;
    const message = error instanceof Error ? error.message : String(error);
    process.stdout.write(
      json
        ? serialize({ error: message, exitCode, ok: false, status: "failed" })
        : `${message}\n`
    );
    return exitCode;
  }
};
